# Generated by Django 2.2.2 on 2019-06-28 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polygons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='created_by',
        ),
    ]
